FROM jakobho/docker-gocd-agent-maven:latest

RUN curl -sL https://deb.nodesource.com/setup_8.x | -E bash -
RUN apt-get install -y nodejs

RUN apt-get install -y golang

RUN apt-get install -y build-essential
